server:
  port: 8081
keycloak:
  realm: Spotimatch
  auth-server-url: http://auth.spotimatch.tk/auth
  resource: spotimatch-api
  public-client: true
  ssl-required: external
  bearer-only: true
  use-resource-role-mappings: true
  #  credentials.secret: 0d7dc4dd-61af-445d-a503-74fb6674313e
  #  use-resource-role-mappings: true
  enabled: true
  securityConstraints:
    - authRoles: [user, admin, user-api]
      securityCollections:
        - name: API Private Data
          patterns: ['/test/*']
    - authRoles: [admin]
      securityCollections:
        - name: API
          patterns: ['/todos/*']