server:
  port: 8081
keycloak:
  realm: Spotimatch
  auth-server-url: http://auth.spotimatch.tk/auth
  resource: spotimatch-api
  public-client: true
  use-resource-role-mappings: true
  cors: true
  cors-max-age: 0
  principal-attribute: preferred_username
  cors-allowed-methods: POST, PUT, DELETE, GET
  cors-allowed-headers: X-Requested-With, Content-Type, Authorization, Origin, Accept, Access-Control-Request-Method, Access-Control-Request-Headers