spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
